services:
  mongodb:
    image: mongo:5.0
    container_name: premium-estate-mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - premium-estate-mongo-data:/data/db

volumes:
  premium-estate-mongo-data:
    name: premium-estate-mongo-data
