export const createRoute = ({
  name,
  layout,
  path,
  component,
  icon,
  under,
  parentName,
  both,
  i18nKey,
}) => ({
  name,
  layout,
  path,
  component,
  ...(icon ? { icon } : {}),
  ...(under ? { under } : {}),
  ...(parentName ? { parentName } : {}),
  ...(both ? { both } : {}),
  ...(i18nKey ? { i18nKey } : {}),
});
